```{r echo=FALSE}
library(GA)
library(knitr)
opts_chunk$set(
  #cache.path = "../../../target/cache/",
  message = FALSE, tidy = FALSE,
  #fig.path = "../../../target/figures/",
  #base.dir = "../../../target/",
  animation.fun = hook_r2swf
)
```
Overview
========
Following libraries will be used
```{r}
#source('./ML_Lab1.R')
```
Set random seed for reproducible experiments.
```{r}
set.seed(1)
```

---
title: "ML_Lab1_report"
output: html_document
---

```{r}
f <- function(x)  (x^2 + x) * cos(x)
min <- -10
max <- +10
curve(f, min, max)
fitness <- function(x) -f(x)
GA <- ga(type = "real-valued", fitness = fitness, min = min, max = max)
plot(GA)
summary(GA)
monitor <- function(obj) {
  curve(f, min, max, main = paste("iteration =", obj@iter), font.main = 1)
  points(obj@population, -obj@fitness, pch = 20, col = 2)
  rug(obj@population, col = 2)
  #Sys.sleep(0.2)
}
```
```{r, ga-animation-1, fig.show='animate', interval=0.2}
GA <- ga(type = "real-valued", fitness, min = min, max = max, monitor = monitor)
```
```{r}
opt.sol <- optimize(f, lower = min, upper = max, maximum = FALSE)
nlm.sol <- nlm(function(...) -f(...), 0, typsize = 0.1)
```
``` {r, echo=FALSE}
curve(f, min, max)
points(GA@solution, GA@fitnessValue*-1, col = 2, pch = 20)
points(opt.sol$minimum, opt.sol$objective, col = 3, pch = 8)
points(nlm.sol$estimate, -nlm.sol$minimum, col = 4, pch = 17)
legend(x = -5, y = -30, legend = c("ga", "optimize", "nlm"), title = "Solutions", pch = c(20,8,17), col = 2:4)
```
```{r}
Rastrigin <- function(x1, x2) {
  20 + x1^2 + x2^2 - 10*(cos(2*pi*x1) + cos(2*pi*x2))
}
x1 <- x2 <- seq(-5.12, 5.12, by = 0.1)
f <- outer(x1, x2, Rastrigin)
```
```{r, echo=FALSE}
persp3D(x1, x2, f, theta = 50, phi = 20)
```
```{r, echo=FALSE}
filled.contour(x1, x2, f, color.palette = jet.colors)
monitor <- function(obj) {
  contour(x1, x2, f, drawlabels = FALSE, col = gray(0.5))
  title(paste("iteration =", obj@iter), font.main = 1)
  points(obj@population, pch = 20, col = 2)
  #Sys.sleep(0.2)
}
```
```{r, ga-animation-2, fig.show='animate', interval=0.2}
GA <- ga(type = "real-valued",
  fitness = function(x) -Rastrigin(x[1], x[2]),
  min = c(-5.12, -5.12), max = c(5.12, 5.12), popSize = 50,
  maxiter = 100, monitor = monitor)
```
```{r, echo=FALSE}
summary(GA)
```
```{r}
NLM <- nlm(function(x) Rastrigin(x[1], x[2]), GA@solution)
NLM[c("minimum", "estimate")]
```
